name 'puppet-pgpool2'
version '0.2.0'
source 'git://github.com/jrodriguezjr/puppet-pgpool2.git'
author 'jrodriguezjr'
license 'Apache License, Version 2.0'
summary 'PostgreSQL pgpool-II defined resource types'
description 'PostgreSQL pgpool-II defined resource types. Supported OSes: Debian'
project_page ''https://github.com/jrodriguezjr/puppet-pgpool2''

dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'puppetlabs/concat', '>=2.0.0'
